### ISSUE TITLE
Colour of Section Headers

### ISSUE THREAD

**Issue by d10** [lodash/lodash.github.io#10]
[Migrated from https://github.com/d10/lodash-docs-experiment/issues/3]

> [Migrated from lodash/lodash#829]  
I recently noticed that the documentation had had its colour theme changed. I've tried to work with it for a few hours, but the purple colour of the section header keeps distracting the eyes away from the actual documentation. Can it be changed to something more neutral?  
The white earlier had been OK in that sense.

By @kumarharsh

**Comment by d10** [comment]
[Migrated from https://github.com/d10/lodash-docs-experiment/issues/3]

> Also more bikeshed, purple is nice but maybe it should match closer to our logo: 
   ![logo](https://avatars0.githubusercontent.com/u/2565403?v=3&s=200)

By @jdalton

**Comment by jdalton** [comment]
I'm fine closing this.
