### ISSUE TITLE
Safari 9.0.2 won't scroll the side-nav-bar sometimes

### ISSUE THREAD

**Issue by DomiR** [lodash/lodash.github.io#12]
So the left sidebar will stop scrolling after the right side was scrolled down. Somehow only the main content will scroll after that, even when hovering the sidebar. The sidebar will only start scrolling again after scrolling the main content to the top. 

Chrome does not have this issue. I noticed that Chrome will always show the scrollbars on both, while Safari hides them. Maybe there is a css fix.

**Comment by thealjey** [comment]
I don't know if this is just a coincidence, but after removing `overflow-x: hidden;` from `#docs .toc-container` through safari developer tools, I'm no longer experiencing this issue.
I have not found a direct correlation though, because this issue seems to appear randomly.

**Comment by jdalton** [comment]
Moved to #17.
