### ISSUE TITLE
Minor bug in example code.

### ISSUE THREAD

**Issue by mik01aj** [lodash/lodash.github.io#13]
I post a screenshot because I don't know where to find a code so I can make a PR:

![image](https://cloud.githubusercontent.com/assets/3027415/12295046/cf3f421e-b9fe-11e5-9a43-36de589f957d.png)

**Comment by jdalton** [comment]
Thanks, this has been reported will push a release today sometime.

**Comment by jdalton** [comment]
Related to https://github.com/lodash/lodash/pull/1763 and https://github.com/lodash/lodash/pull/1762.
