### ISSUE TITLE
lazy evaluation link broken

### ISSUE THREAD

**Issue by avimar** [lodash/lodash.github.io#14]
Features -> Lazily evaluated chaining links to:
http://filimanjaro.com/blog/2014/introducing-lazy-evaluation/
.. which isn't a blog entry.

Cached link without images...
http://webcache.googleusercontent.com/search?q=cache:qFWWEei6eHUJ:filimanjaro.com/blog/2014/introducing-lazy-evaluation/+&cd=1&hl=en&ct=clnk&gl=il

**Comment by jdalton** [comment]
Sites go down from time to time. It was up recently so let's not jump the gun.
\cc @FilipZawada

**Comment by jdalton** [comment]
@avimar It's back ;)
