### ISSUE TITLE
lodash website/docs redesign

### ISSUE THREAD

**Issue by veksen** [lodash/lodash.github.io#15]
Hello, after the discussion about #8, a lot of talk has been about the doc generation itself, but none about the design or the interface, so I'm opening this issue. I will be suggesting something in the next few days, but until then, I'd still like to document what Lodash's website and docs are heading to:

- Clean
- Responsive/mobile friendly
- Mobile menu (hamburger), maybe swipable on/off
- Logo... maybe tweaked a little bit

For the docs: 
- Searchable
- Improved readability
- Methods linking to a REPL

Extra info:
- Docs are based on https://github.com/lodash/lodash/blob/4.5.0/doc/README.md
- Keep in mind most of the users are devs, and the majority of the traffic comes for the doc

Help, suggestion or contribution is nice. If you have something in mind, Photoshop renders work, too!

**Comment by jdalton** [comment]
Thanks for starting this @veksen!

**Comment by veksen** [comment]
Alright, I'm overdue, but still not 100% sure, especially with the website. For the most part, I reused the structure of the actual website.

Website:
![lodash-1col](https://cloud.githubusercontent.com/assets/3461986/14658255/69a75f96-0660-11e6-870f-97a44b2f1834.png)

Docs:
![sketch-lodash-docs](https://cloud.githubusercontent.com/assets/3461986/14658269/84b8f682-0660-11e6-8ac1-2eafe64a83fa.png)

**Comment by jdalton** [comment]
The mockups look great. I'd give the FP-Guide button equal-ish padding (some rounded color) on the home page. The color scheme for docs is super nice.

**Comment by veksen** [comment]
![lodash-1col](https://cloud.githubusercontent.com/assets/3461986/14661606/f20b53c6-067c-11e6-8877-8a6f24d28524.png)

**Comment by jdalton** [comment]
@veksen Yeah!

**Comment by veksen** [comment]
@jdalton not entirely sure on that color, but you get the idea

**Comment by veksen** [comment]
If this is the direction we are going, where do I start to start integrating this? Should I be in touch with @justinhelmer ?

**Comment by jdalton** [comment]
>  Should I be in touch with @justinhelmer ?

Yep!

**Comment by justinhelmer** [comment]
@veksen - Looks great! 

[this fork](https://github.com/justinhelmer/lodash.github.io) has all the build tools. Documentation is pretty up-to-date.

You should be able to pull it down & update whatever templates/CSS you need for the website itself.

The documentation is currently built with [jsdoc3](http://usejsdoc.org/). Unfortunately, the [default template options](http://usejsdoc.org/about-configuring-default-template.html) are quite limited, and the default template does not support all tags used by the `lodash` team (i.e. the `*@category*` tag, which is not officially supported by `jsdoc`).

The other option is to [build a custom jsdoc template](https://github.com/jsdoc3/jsdoc/tree/master/templates), which uses [TaffyDB](http://www.taffydb.com/). However, other users such as @clenemt have [had success](https://www.npmjs.com/package/docdash), and may be able to provide some insight. In fact, the fork repo currently uses his `docdash` theme.

**Comment by veksen** [comment]
@justinhelmer I'll start with this! Thanks!

**Comment by veksen** [comment]
@justinhelmer Where do I reach out? I installed grm globally, and `npm start` fails to build, other commands are also failing for different reasons. node -v 5.10.0 nodejs -v 5.10.1 npm -v 3.8.3

**Comment by clenemt** [comment]
Wow nice theme :+1: @veksen.
I will definitely update [docdash ](https://github.com/clenemt/docdash)to match this baby!
I'll keep you in the loop (this weekend maybe?)

**Comment by justinhelmer** [comment]
@veksen - can you be more specific with your issues? Did you do `npm install`? 

@daannijkamp is also interested in helping wrap this up.

Let me know how I can help, although at the moment my time is limited

**Comment by veksen** [comment]
@justinhelmer @daannijkamp I did run `npm install`. I tried both node 5.10.0 and 4.4.3. It still fails to build. I'm not a novice with npm - it's part of my daily workflow - but not an expert either.

**Comment by jdalton** [comment]
@veksen Could you provide the fonts, and mock up sources?

**Comment by veksen** [comment]
@jdalton no problem, sent you a message on Gitter

**Comment by jdalton** [comment]
Closed by #18!
