### ISSUE TITLE
'&' character escaped into '&amp;' in code blocks of documentation page

### ISSUE THREAD

**Issue by yvele** [lodash/lodash.github.io#16]
In [isEqualWith](https://lodash.com/docs#isEqualWith) and [isMatchWith](https://lodash.com/docs#isMatchWith) code examples, the **&&** operator is escaped to **\&amp;\&amp;**

https://lodash.com/docs#isEqualWith

````JS
...
function customizer(objValue, othValue) {
  if (isGreeting(objValue) &amp;&amp; isGreeting(othValue)) {
    return true;
  }
}
...
````

https://lodash.com/docs#isMatchWith

````JS
...
function customizer(objValue, srcValue) {
  if (isGreeting(objValue) &amp;&amp; isGreeting(srcValue)) {
    return true;
  }
}
...
````

**Comment by jdalton** [comment]
Fixed. Thanks!
