### ISSUE TITLE
Build step for JavaScript

### ISSUE THREAD

**Issue by demoneaux** [lodash/lodash.github.io#26]
Any plans for a build step (probably Babel/webpack) for the docs JS? I don't think loading the Babel transformer for each page is a good idea.

**Comment by jdalton** [comment]
It's a bit much and not totally needed. The doc.js could be written as non ES6.

**Comment by demoneaux** [comment]
Cool, that’s what I was thinking. The docs kinda felt a little sluggish to me on mobile. Are you up with a PR for that?
