### ISSUE TITLE
`_` is not working in Chrome DevTools anymore (Chrome  52.0.2743.116 m)

### ISSUE THREAD

**Issue by herom** [lodash/lodash.github.io#39]
`_` is not working on the CLI of Chrome DevTools if you are on the `/docs` page. Instead of getting a grip on `lodash` it will return the HTML Element with the matching ID instead (`<h3 id="_">`). If you access it with `window._` it is available as usual.

After accessing it with `window._` once, it will be available as `_` as well...

**Comment by jdalton** [comment]
Hi @herom!

Clear your cache and try again.

**Comment by herom** [comment]
this is reproducible... close the tab and access the page again - you will see the same behaviour...

**Comment by jdalton** [comment]
Yep, I've hit it before too and clearing your cache tends to fix it. It's some weird condition with the auto global of the `<div id="_">` where most of the time the Lodash `_` trumps it but sometimes it doesn't after page load.

**Comment by jdalton** [comment]
I went ahead and patched it since it's easier than digging into it. https://github.com/lodash/lodash.github.io/commit/918fdf5776a0572ebfa39906883bcefcf2b825dd

**Comment by herom** [comment]
thanks a ton :+1: :smiley_cat:

**Comment by jdalton** [comment]
Related to https://github.com/lodash/lodash/issues/2120.
