### ISSUE TITLE
Font size and color makes method names hard to read

### ISSUE THREAD

**Issue by calvinf** [lodash/lodash.github.io#44]
I'm having a harder time reading the method names in the Lodash docs due to the small font size.

Selector: `html.docs .toc-container ul li a`

font-size is currently 0.8em; I have an easier time reading it when I tweak it to 1.0em.

I'd have to check to be sure, but the font color may not meet accessibility standards for contrast.  It looks a bit light to me, but I haven't pulled out a contrast checker to verify yet.

**Comment by jdalton** [comment]
Moved to #43.

**Comment by jdalton** [comment]
Hi @calvinf! I've moved this to #43 for incorporate into the PR @veksen is working on.
