### ISSUE TITLE
Browser locks while loading Lodash docs

### ISSUE THREAD

**Issue by calvinf** [lodash/lodash.github.io#45]
When I load the Lodash docs, my browser freezes for several seconds.

Repro steps:
* Navigate to docs from Lodash homepage (click [Documentation](https://lodash.com/docs/4.15.0) link)
* Browser (Firefox 48.0.1) freezes for a few seconds
* Switch versions (to 3.10.1 or 2.4.2)
* Browser freezes for a few seconds

Something about how the docs are being loaded is slowing things down.  I haven't had time to dig in and find out why.

**Comment by jdalton** [comment]
It looks CSS related but not sure what's causing it (there's plenty of places for it to buckle down on).

**Comment by calvinf** [comment]
In glancing through the JS, it may be related to initializing React state
by parsing the DOM. The selectors could be more efficient, and some
debouncing may avoid it locking up. Not sure if that's root cause but
something to check.

**Comment by jdalton** [comment]
If I remove all JS on the page it still locks up. If I removed the CSS the page loads w/o locking up.

**Comment by jdalton** [comment]
If you come up with anything let me know.
For now it's just one of those things I hope gets better with time.

**Comment by ivan-kolmychek** [comment]
Just stumbled upon the same issue, disabling the CSS helps.

From quick "performance" run that I was able to do in Firefox, it spends a lot of time in styles.

**Comment by ivan-kolmychek** [comment]
![screenshot_20160906_190453](https://cloud.githubusercontent.com/assets/5011577/18281435/830596c4-7465-11e6-899c-521d6e072dc3.png)

**Comment by jdalton** [comment]
\cc @bzbarsky

**Comment by zackhall** [comment]
My initial thought was similar to @calvinf's: maybe initializing the react state by reading, parsing the DOM was locking it up and retriggering layouts.

However, it's heavy layout cycles of 40-80ms causing this that are triggered _before_ the initial render from docs.js. 

In screenshot below, initial evaluation of the javascript is the blue bar, and sub-details, on the right. The layouts are the purple blocks.

![image](https://cloud.githubusercontent.com/assets/1725349/18291500/d1b5585a-743c-11e6-90a7-9950554b6a52.png)

**Comment by bzbarsky** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1300939

**Comment by bzbarsky** [comment]
And in particular, it's something about the combination of flex from main.css and something the fontawesome stylesheet is doing that causes the slowdown in Firefox.  Not clear what yet.

**Comment by jdalton** [comment]
@bzbarsky Thank you so much for digging into this!

**Comment by bzbarsky** [comment]
@jdalton Thanks for letting me know about it!

**Comment by linonetwo** [comment]
It's getting slow again! In chrome.

**Comment by jdalton** [comment]
Nothing has changed on our end. If you think it's a Chrome regression you're better off filing the bug with Chrome since I'm not going to do any work on this.

**Comment by bbottema** [comment]
@jdalton, It's become completely unusable for me. Locks up for a minute.

**Comment by jdalton** [comment]
I'm locking the thread since "met too" comments without a patch or further info don't really help. I've visited the docs in Chrome plenty of times and have never had a problem with it.
