### ISSUE TITLE
Lodash itself is not loaded on the documentation page.

### ISSUE THREAD

**Issue by nkcmr** [lodash/lodash.github.io#46]
A very minor issue, but before the update, Lodash was present on the documentation page. I liked this because while looking up docs I could just open the inspector and play around and see how Lodash behaved.

**Comment by jdalton** [comment]
Hi @nkcmr 

See https://twitter.com/jdalton/status/771357643025752064.

**Comment by nkcmr** [comment]
@jdalton gahh! gets me everytime. sorry if i am the millionth person to open this issue.

**Comment by blowsie** [comment]
@jdalton,  Thanks for this.

However, whilst this change is explained, is it possible to expose it again? or should some documentation be added? I wonder how many other duplicate tickets will have this same request / how many other users end up on this page.

**Comment by jdalton** [comment]
@blowsie It's a Chrome bug. See https://twitter.com/jdalton/status/771371260672561152. You literally have to move your mouse to the context drop-down list in Chrome's developer JavaScript console and select "top".

<img src="https://cloud.githubusercontent.com/assets/4303/18251373/b220ffb2-733d-11e6-9827-6806f6658771.gif" height=40% width=40%>

**Comment by blowsie** [comment]
@jdalton aha! thanks for the explanation

**Comment by rgbkrk** [comment]
How about an intro explanation to the console log on entry for now?

**Comment by nkcmr** [comment]
@rgbkrk not exactly possible because the arbitrary contexts that are switched to in chrome are not in the control of @jdalton. they usually belong to extensions installed in your browser. we just have to wait for the big to be fixed in chrome.

**Comment by rgbkrk** [comment]
Ohhhhh

**Comment by craigmichaelmartin** [comment]
`console.log("If _ is not defined, see https://github.com/lodash/lodash.github.io/issues/46");` Could be removed after the chrome bug is fixed.

**Comment by mohsen1** [comment]
Submitted a bug for this: https://bugs.chromium.org/p/chromium/issues/detail?id=647800&can=2&q=service%20worker%20top%20&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by jdalton** [comment]
@mathiasbynens There's already [a couple](https://twitter.com/jdalton/status/771371260672561152).
