### ISSUE TITLE
Docs broken on Firefox

### ISSUE THREAD

**Issue by zackhall** [lodash/lodash.github.io#48]
The list of functions in the TOC container has all empty HTML elements (no method name) on Firefox...

![image](https://cloud.githubusercontent.com/assets/1725349/18194627/e2fe2d5c-709b-11e6-8a9e-de6565117f81.png)

**Comment by zackhall** [comment]
Seems like it could be related to the Immutable JS change. 

```js
collection.get('title') //undefined
```

**Comment by jdalton** [comment]
What version of Firefox are you on?

**Comment by jdalton** [comment]
FF48
<img width="443" src="https://cloud.githubusercontent.com/assets/4303/18196095/4e8d81be-70a4-11e6-9ed8-0d1155f14682.png">

**Comment by zackhall** [comment]
Yeah, you're right. My Firefox was still on 42... Updated and is working okay again.

**Comment by jdalton** [comment]
This is because Firefox added `innerText` support in 45.
