### ISSUE TITLE
Janky scrolls on both desktop and mobile

### ISSUE THREAD

**Issue by tusharmath** [lodash/lodash.github.io#50]
Highlight js creates tons of layers per code block. This makes layer recomposition take a lot of time. I think a decent solution would be to disable layers at the time of scrolling by adding a css class name on the root component.

**Comment by jdalton** [comment]
I'm also looking into reducing the [highlights](https://github.com/atom/highlights) markup.

**Comment by jdalton** [comment]
Hi @tusharmath!

I can't repro but this looks related to #41. If you're up for creating a PR I'm cool with it.

**Comment by tusharmath** [comment]
@jdalton They are only made when you reduce the screen size.

<img width="1434" alt="screen shot 2016-09-04 at 11 47 27 am" src="https://cloud.githubusercontent.com/assets/194482/18229390/66e196a4-7295-11e6-8a0d-072930dc4cf9.png">

**Comment by jdalton** [comment]
So then not when scrolling?

**Comment by tusharmath** [comment]
I mean the layers are always there which causes the performance issue while scrolling.

**Comment by jdalton** [comment]
Ya, I get that but, I can't repro your scroll perf issue.
If you'd like to fix the issue and submit a PR that would be great otherwise this will likely go unfixed.

**Comment by tusharmath** [comment]
Cool, will give it a shot when I get time.
