### ISSUE TITLE
Module sidebar is broken on Iceweasel 38.7.1

### ISSUE THREAD

**Issue by emdeha** [lodash/lodash.github.io#51]
Hey, just noticed this behavior on the above mentioned browser. I saw no errors in the dev console.

![lodash-bogus-sidebar](https://cloud.githubusercontent.com/assets/1549442/18209616/320a8124-713d-11e6-9b0d-4d80572d197a.png)

**Comment by jdalton** [comment]
Hi @emdeha!

I'm OK with not supporting off brand browsers. See https://github.com/lodash/lodash.github.io/issues/48.

That said, if you provide a PR to fix it, I'll accept it.

**Comment by emdeha** [comment]
@jdalton thanks for the clarification :) I see you've fixed the issue anyway :bow:
