### ISSUE TITLE
Old interface of https://lodash.com/docs

### ISSUE THREAD

**Issue by aggarwalankush** [lodash/lodash.github.io#53]
Is there any way to use old interface of https://lodash.com/docs?

**Comment by jdalton** [comment]
Hi @aggarwalankush!

Nope. The old inferface is dead and gone.

You can always view the markdown flavor of the docs:
https://github.com/lodash/lodash/tree/4.15.0/doc

**Comment by zackhall** [comment]
What did you like about the old interface @aggarwalankush? Were there specific features or aspects of it that were very helpful to you that you feel are missing on the new site? Or was it just familiarity?

**Comment by aggarwalankush** [comment]
@zackhall First of all I appreciate the new interface and time everyone must have spent on it.

Without being rude, I would like to share some problems I'm facing with the new interface.
- If I search for some function from search bar on top left and click on search result, it clears the search bar and there is no way to see all functions back. Have to refresh url every time.
![screenshot 2016-09-02 11 40 13 3](https://cloud.githubusercontent.com/assets/8744282/18214465/0c048a8c-7102-11e6-88b2-ac3eb50cdf45.png)

- In description of each function, I can't click on other functions reference to jump to that function.
In screenshot, description has reference to _.difference and _.pullAllBy which are not clickable
![screenshot 2016-09-02 11 41 21 3](https://cloud.githubusercontent.com/assets/8744282/18214503/2fd642b6-7102-11e6-96b6-da831569fc66.png)

-Thanks

**Comment by zackhall** [comment]
Thanks for taking the time to give constructive feedback, @aggarwalankush. 

Re: issue 1: I noticed this myself and currently working on a PR for it. Look for that fix soon.

Re: issue 2: That's great feedback. Focused currently on smoothing out some of the other issues but will keep that in mind. In the meantime, if you'd like to make a PR we'd be happy to accept it.

**Comment by ivan-kolmychek** [comment]
I don't want to resurrect already closed issue, but it feels that it's too minor of a comment to create a new one - previous interface was MUCH more faster for me. 

Right now, if I just open the documentation, it will freeze the whole browser for ~9-10 seconds and is really annoying. I don't really know what is causing that problem and why one tab of new lodash docs alone is doing what ~200 *simultaneously* open tabs couldn't do before. 

Thanks for pointing out to markdown version on Github, it opens around ~3 seconds for me, which is much more usable. 
I think there should be a second link near documentation button on `lodash.com` pointing to that version too. :)

**Comment by ivan-kolmychek** [comment]
Oh, I see, there is #45 for this. Sorry to hijack the thread then, I'll go there. :)
