### ISSUE TITLE
Default font size

### ISSUE THREAD

**Issue by jdalton** [lodash/lodash.github.io#57]

**Comment by zackhall** [comment]
Can you attach some more details here, @jdalton?

**Comment by jdalton** [comment]
See https://github.com/lodash/lodash.github.io/pull/43#issuecomment-244517655.

**Comment by jdalton** [comment]
\cc @veksen

**Comment by veksen** [comment]
@zackhall I will tackle this. Do we agree to use `rem` everywhere (at least with the fonts)? There's very few `em` uses, so it shouldn't be too hard to convert.

Also, a very nice way to handle this, is to set the html font-size to 62.5% (aka 10px), then have a natural scaling using `rem` on a base 10 (1.4rem = 14px). IE8 doesn't support `rem`, so we have to define a fallback: `font-size: 14px; font-size: 1.4rem;`. Note that IE9-10 support `rem`, but it has a bug with it used in a font shorthand, causing it to completely ignore the definiton (http://caniuse.com/#feat=rem).

We can use a sass mixin to convert `px` to `rem`, while adding the fallback.

**Comment by jdalton** [comment]
No need for fallbacks.

**Comment by jdalton** [comment]
Moved to #62.
