### ISSUE TITLE
TOC covers the content

### ISSUE THREAD

**Issue by JakeCoxon** [lodash/lodash.github.io#58]
![image](https://cloud.githubusercontent.com/assets/601264/18280045/f74d445c-7481-11e6-8c34-57e657c5578c.png)

This is on Chrome Version 52.0.2743.116 and Firefox 47.0.1 on Mac OSX 10.11.1

**Comment by jdalton** [comment]
Can you try clearing your page cache and trying again.

**Comment by jdalton** [comment]
Patched https://github.com/lodash/lodash.github.io/commit/974b59dce7fc76d8c66d5bfd81bb6d79e02d7d16.

**Comment by dferber90** [comment]
Works now 👍
