### ISSUE TITLE
Left navigation overlaps content

### ISSUE THREAD

**Issue by dferber90** [lodash/lodash.github.io#59]
This happens in the following browsers which I've tested:
- Firefox 45.0.2
- Chrome Version 52.0.2743.116 (64-bit)
- Safari Version 9.1.2 (11601.7.7)

I'm using a Mac.

![bildschirmfoto 2016-09-06 um 17 35 20](https://cloud.githubusercontent.com/assets/1765075/18280138/5693c08c-7458-11e6-963b-2ffaf101ac72.png)

**Comment by jdalton** [comment]
Dup of #58.
