### ISSUE TITLE
(iOS) TOC: intermittent scrolling behavior

### ISSUE THREAD

**Issue by veksen** [lodash/lodash.github.io#66]
It's hard to completely identify the issue here, but here are the key points:

1. An initial page load will always be fine
2. Sometimes, opening the menu will cause touch actions to be stuck in horizontal scrolling instead of vertical scrolling.
3. A single tap on the screen will always resolve it.

**Comment by jdalton** [comment]
I've tweaked the styles to remove the `calc` from the width which lets it size to whatever it needs.
This should remove the horizontal scroll of the menu.
