### ISSUE TITLE
Cache busting main.css and docs.js

### ISSUE THREAD

**Issue by veksen** [lodash/lodash.github.io#69]
With the constant updates to the site/docs, it would be nice to cache bust via filename.

I could do this. I'm fairly familiar on how to do it with gulp-rev, but I'm not completely familiar with Jekyll and how to pull in those revisions from a json file (or perhaps it needs to be added to a/the yml file?), so I could use some input.

**Comment by jdalton** [comment]
I cache bust in the service worker layer but ya we could add cache busting to the other references.

**Comment by jdalton** [comment]
I recently [removed our busting code](https://github.com/lodash/lodash.com/commit/a7f94b3f07f625f89407d13c8e9df1b9965ccb88) to rely on ETags instead. So far so good.
