### ISSUE TITLE
Ability to jump to a method in documentation

### ISSUE THREAD

**Issue by nmehta6** [lodash/lodash.github.io#7]
It would be great if thre was an easier way to navigate the documentation with search. An autocomplete search would be a start. Please let me know if I am opening the issue in the correct project.

**Comment by jdalton** [comment]
I've seen something like [this](https://github.com/davidshimjs/jaguarjs-jsdoc) before. I'd accept a PR on it.

**Comment by nmehta6** [comment]
Great. Let me see if I can put something together.
