### ISSUE TITLE
Manifest.json file is needed for add to home screen

### ISSUE THREAD

**Issue by gokulkrishh** [lodash/lodash.github.io#73]
**Why ?**

Site and document is updated with offline support is great. But no manifest.json file is present to add lodash to home screen.

**Comment by jdalton** [comment]
Hi @gokulkrishh!

Would you like to create a PR to add it?

**Comment by gokulkrishh** [comment]
@jdalton Yep I have already forked and added the icons + manifest. Testing it locally. Will push a PR  once done 👍

**Comment by jdalton** [comment]
Moved to #74.
