### ISSUE TITLE
Logo Suggestions

### ISSUE THREAD

**Issue by Omar12** [lodash/lodash.github.io#9]
I wanted to give a try on some logo concepts for lodash. Feedback is highly appreciated.

**Logo Concept 1**
<img src=https://cloud.githubusercontent.com/assets/448663/11140732/a9d40204-8992-11e5-9db6-aa24dff3a29e.png height=25% width=25%>

**Logo Concept 2**
<img src=https://cloud.githubusercontent.com/assets/448663/11140731/a9d1adba-8992-11e5-9a7c-a479f3421047.png height=25% width=25%>

**Logo Concept 3**
<img src=https://cloud.githubusercontent.com/assets/448663/11140733/a9d6672e-8992-11e5-86c7-79b123c53429.png height=25% width=25%>

Feel free to add your logo concepts here.

**Comment by jdalton** [comment]
Thank you @Omar12!

**Comment by Omar12** [comment]
@jdalton no problem!

**Comment by Omar12** [comment]
Another suggested variation:
![logo_4](https://cloud.githubusercontent.com/assets/448663/11167089/bffa025a-8b08-11e5-8fc1-f54f83221d09.png)

**Comment by jdalton** [comment]
Thanks for these logos @Omar12!
While we aren't actively looking to change I always dig a fresh take on things.

**Comment by jdalton** [comment]
If you have other ideas feel free to post them (even if the issue is closed).

**Comment by Omar12** [comment]
Sounds good! :thumbsup:
